//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63134085.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChiTietHDB
    {
        public int ID { get; set; }
        public string MaHoaDon { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<decimal> DonGiaBan { get; set; }
        public string GhiChu { get; set; }
        public string TenSP { get; set; }
        public string AnhDaiDien { get; set; }
        public string Loai { get; set; }
    
        public virtual tDanhMucSP tDanhMucSP { get; set; }
        public virtual tHoaDonBan tHoaDonBan { get; set; }
    }
}
