//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63134085.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tHoaDonBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tHoaDonBan()
        {
            this.tChiTietHDBs = new HashSet<tChiTietHDB>();
        }
    
        public string MaHoaDon { get; set; }
        public Nullable<System.DateTime> NgayHoaDon { get; set; }
        public string MaKhachHang { get; set; }
        public Nullable<decimal> TongTienHD { get; set; }
        public string GhiChu { get; set; }
        public string Ten { get; set; }
        public string TrangThai { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tChiTietHDB> tChiTietHDBs { get; set; }
        public virtual tKhachHang tKhachHang { get; set; }
    }
}
