//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63134085.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;

	public partial class tKhachHang
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public tKhachHang()
		{
            this.tGioHangs = new HashSet<tGioHang>();
            this.tHoaDonBans = new HashSet<tHoaDonBan>();
        }

		[Key, Column(Order = 1)]
		[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
		public string MaKhanhHang { get; set; }
		[DisplayName("Tài khoản")]
		[Required(ErrorMessage = "Vui lòng không để trống.")]
		public string username { get; set; }
		[DisplayName("Mật khẩu")]
		[Required(ErrorMessage = "Vui lòng không để trống.")]
		public string password { get; set; }
		[Compare("password", ErrorMessage = "Mật khẩu nhập lại không khớp.")]
		[DisplayName("Nhập lại mật khẩu")]
		[Required(ErrorMessage = "Vui lòng không để trống.")]
		public string confirmpassword { get; set; }
		[DisplayName("Họ và tên")]
		[Required(ErrorMessage = "Vui lòng không để trống.")]
		public string TenKhachHang { get; set; }
		[DisplayName("Ngày sinh")]
		[Required(ErrorMessage = "Vui lòng không để trống.")]		
		public Nullable<System.DateTime> NgaySinh { get; set; }
		[DisplayName("Số điện thoại")]
		[Required(ErrorMessage = "Vui lòng không để trống.")]
		[RegularExpression(@"^\d+$", ErrorMessage = "Vui lòng nhập đúng định dạng.")]
		public string SoDienThoai { get; set; }
		[DisplayName("Địa chỉ")]
		[Required(ErrorMessage = "Vui lòng không để trống.")]
		public string DiaChi { get; set; }
		public string AnhDaiDien { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGioHang> tGioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tHoaDonBan> tHoaDonBans { get; set; }
    }
}
